### ISSUE TITLE
[theme][design] mobile nav should center items

### ISSUE THREAD

**Issue by josefaidt** [josefaidt/josefaidt.github.io#32]
Mobile nav looks odd with only two items
![image](https://user-images.githubusercontent.com/5033303/66416241-fda6b900-e9c2-11e9-9073-63a41d272860.png)

- center them? grid?
- nav container in mobile should also have a relatively static height. Currently it is calculated based on the viewport, which can cause overflow issues on smaller devices.

**Comment by josefaidt** [comment]
```css
@media screen and (max-width: 768px) {
  display: grid;
  grid-auto-flow: column;
  grid-template-columns: repeat(auto-fit, minmax(5rem, 1fr));
  grid-gap: 0.5rem;
  padding: 0 1rem;
  height: 4rem;
}
```

![image](https://user-images.githubusercontent.com/5033303/66420599-c38de500-e9cb-11e9-8fbf-3eefd99f2acf.png)

will need to adjust the mobile footer offset as well
